package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private String type;
     private Set logses = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(String name, String username, String password, String type) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.type = type;
    }
    public Accounts(String name, String username, String password, String type, Set logses) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.type = type;
       this.logses = logses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getLogses() {
        return this.logses;
    }
    
    public void setLogses(Set logses) {
        this.logses = logses;
    }




}


