package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FactoryStatus generated by hbm2java
 */
public class FactoryStatus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date nowTime;

    public FactoryStatus() {
    }

    public FactoryStatus(String name, Date nowTime) {
       this.name = name;
       this.nowTime = nowTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getNowTime() {
        return this.nowTime;
    }
    
    public void setNowTime(Date nowTime) {
        this.nowTime = nowTime;
    }




}


