package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logs generated by hbm2java
 */
public class Logs  implements java.io.Serializable {


     private Integer id;
     private Accounts accounts;
     private String action;
     private Date time;

    public Logs() {
    }

    public Logs(Accounts account, String action, Date time) {
       this.accounts = account;
       this.action = action;
       this.time = time;
    }
    
    public Logs(int id, Accounts accounts) {
        this.id = id;
        this.accounts = accounts;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


