package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1



/**
 * OrderProductsId generated by hbm2java
 */
public class OrderProductsId  implements java.io.Serializable {


     private int orderId;
     private int stockId;

    public OrderProductsId() {
    }

    public OrderProductsId(int orderId, int stockId) {
       this.orderId = orderId;
       this.stockId = stockId;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getStockId() {
        return this.stockId;
    }
    
    public void setStockId(int stockId) {
        this.stockId = stockId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderProductsId) ) return false;
		 OrderProductsId castOther = ( OrderProductsId ) other; 
         
		 return (this.getOrderId()==castOther.getOrderId())
 && (this.getStockId()==castOther.getStockId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderId();
         result = 37 * result + this.getStockId();
         return result;
   }   


}


