package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private String requester;
     private int processingOrder;
     private boolean finished;
     private Date targetDate;
     private Set orderProductses = new HashSet(0);

    public Orders() {
    }

    public Orders(String requester, int processingOrder, boolean finished, Date targetDate) {
        this.requester = requester;
        this.processingOrder = processingOrder;
        this.finished = finished;
        this.targetDate = targetDate;
    }
    public Orders(String requester, int processingOrder, boolean finished, Date targetDate, Set orderProductses) {
       this.requester = requester;
       this.processingOrder = processingOrder;
       this.finished = finished;
       this.targetDate = targetDate;
       this.orderProductses = orderProductses;
    }
    
    public Orders(int id, String requester, Date targetDate, boolean finished) {
        this.id = id;
        this.requester = requester;
        this.targetDate = targetDate;
        this.finished = finished;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRequester() {
        return this.requester;
    }
    
    public void setRequester(String requester) {
        this.requester = requester;
    }
    public int getProcessingOrder() {
        return this.processingOrder;
    }
    
    public void setProcessingOrder(int processingOrder) {
        this.processingOrder = processingOrder;
    }
    public boolean isFinished() {
        return this.finished;
    }
    
    public void setFinished(boolean finished) {
        this.finished = finished;
    }
    public Date getTargetDate() {
        return this.targetDate;
    }
    
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }
    public Set getOrderProductses() {
        return this.orderProductses;
    }
    
    public void setOrderProductses(Set orderProductses) {
        this.orderProductses = orderProductses;
    }




}


