package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1



/**
 * OrderProducts generated by hbm2java
 */
public class OrderProducts  implements java.io.Serializable {


     private OrderProductsId id;
     private Orders orders;
     private Stocks stocks;
     private int amount;

    public OrderProducts() {
    }

    public OrderProducts(OrderProductsId id, Orders orders, Stocks stocks, int amount) {
       this.id = id;
       this.orders = orders;
       this.stocks = stocks;
       this.amount = amount;
    }
   
    public OrderProductsId getId() {
        return this.id;
    }
    
    public void setId(OrderProductsId id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Stocks getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Stocks stocks) {
        this.stocks = stocks;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


