package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Processes generated by hbm2java
 */
public class Processes  implements java.io.Serializable {


     private Integer id;
     private Stocks stocks;
     private String name;
     private int resultAmount;
     private float errorChance;
     private Set processStageses = new HashSet(0);

    public Processes() {
    }

	
    public Processes(Stocks stocks, String name, int resultAmount, float errorChance) {
        this.stocks = stocks;
        this.name = name;
        this.resultAmount = resultAmount;
        this.errorChance = errorChance;
    }
    public Processes(Stocks stocks, String name, int resultAmount, float errorChance, Set processStageses) {
       this.stocks = stocks;
       this.name = name;
       this.resultAmount = resultAmount;
       this.errorChance = errorChance;
       this.processStageses = processStageses;
    }

    public Processes(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Stocks getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Stocks stocks) {
        this.stocks = stocks;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getResultAmount() {
        return this.resultAmount;
    }
    
    public void setResultAmount(int resultAmount) {
        this.resultAmount = resultAmount;
    }
    public float getErrorChance() {
        return this.errorChance;
    }
    
    public void setErrorChance(float errorChance) {
        this.errorChance = errorChance;
    }
    public Set getProcessStageses() {
        return this.processStageses;
    }
    
    public void setProcessStageses(Set processStageses) {
        this.processStageses = processStageses;
    }




}


