package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1



/**
 * ProcessMaterials generated by hbm2java
 */
public class ProcessMaterials  implements java.io.Serializable {


     private ProcessMaterialsId id;
     private Stocks stocks;
     private int amount;

    public ProcessMaterials() {
    }

    public ProcessMaterials(ProcessMaterialsId id, Stocks stocks, int amount) {
       this.id = id;
       this.stocks = stocks;
       this.amount = amount;
    }
   
    public ProcessMaterialsId getId() {
        return this.id;
    }
    
    public void setId(ProcessMaterialsId id) {
        this.id = id;
    }
    public Stocks getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Stocks stocks) {
        this.stocks = stocks;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


