package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1



/**
 * ProcessStagesId generated by hbm2java
 */
public class ProcessStagesId  implements java.io.Serializable {


     private int processId;
     private int stageIndex;

    public ProcessStagesId() {
    }

    public ProcessStagesId(int processId, int stageIndex) {
       this.processId = processId;
       this.stageIndex = stageIndex;
    }
   
    public int getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(int processId) {
        this.processId = processId;
    }
    public int getStageIndex() {
        return this.stageIndex;
    }
    
    public void setStageIndex(int stageIndex) {
        this.stageIndex = stageIndex;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessStagesId) ) return false;
		 ProcessStagesId castOther = ( ProcessStagesId ) other; 
         
		 return (this.getProcessId()==castOther.getProcessId())
 && (this.getStageIndex()==castOther.getStageIndex());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProcessId();
         result = 37 * result + this.getStageIndex();
         return result;
   }   


}


