package model;
// Generated May 17, 2017 8:45:27 AM by Hibernate Tools 4.3.1



/**
 * ProcessMaterialsId generated by hbm2java
 */
public class ProcessMaterialsId  implements java.io.Serializable {


     private int processId;
     private int processMaterialId;

    public ProcessMaterialsId() {
    }

    public ProcessMaterialsId(int processId, int processMaterialId) {
       this.processId = processId;
       this.processMaterialId = processMaterialId;
    }
   
    public int getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(int processId) {
        this.processId = processId;
    }
    public int getProcessMaterialId() {
        return this.processMaterialId;
    }
    
    public void setProcessMaterialId(int processMaterialId) {
        this.processMaterialId = processMaterialId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessMaterialsId) ) return false;
		 ProcessMaterialsId castOther = ( ProcessMaterialsId ) other; 
         
		 return (this.getProcessId()==castOther.getProcessId())
 && (this.getProcessMaterialId()==castOther.getProcessMaterialId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProcessId();
         result = 37 * result + this.getProcessMaterialId();
         return result;
   }   


}


